[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "The Azure App Innovation GBB Team", email = ""}]
dynamic = ["version", "description"]
